[package]
name = "b"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iterslide = "1.0.1"

[[bin]]
name = "b"
path = "b.rs"
